module main

import hamza_bpe { please_encode_this }
import hamza_bfe { encrypt_this_please }

fn main() {
    /*
     So my idea is:

     1. we get a message!
     2. bpe.
     3. bfe. (k_vec is autogenerated, s_pos is random)
     (and then, but later) 4. base64.

     Voila!
    */
    my_secret_message := "Hello world, Big brother is watching!"

    encoded_bpe, translation_table := please_encode_this(my_secret_message)

    mut bfe_inst, encrypted_bfe := encrypt_this_please(encoded_bpe)
    println("${my_secret_message} -> ${encoded_bpe} -> ${encrypted_bfe}")
    bfe_inst.decrypt_and_ret(encrypted_bfe)

    mut text := bfe_inst.data
    for x,y in translation_table {
        text = text.replace(y, x)
    }
    println("\n\n${encrypted_bfe} -> ${bfe_inst.data} -> ${text}")

    return
}